### ISSUE TITLE
Remove target subdirectory

### ISSUE THREAD

**Issue by shinabro** [codyhock/se-352-452-group6#3]
You may run into some issues because you already have branches but you most likely will want to remove the target subdirectory since that is a binary that can be recreated.

You need to do 2 things.
1) Add a target in .gitignore file
2) Remove the directory in git
git rm -r target
git commit -m "Remove duplicated directory"
git push origin master (and then you may need to do same for other branches)

**Comment by codyhock** [comment]
did the above instructions and the target directory is gone. closing this issue.
